all: examples

examples:
	mkdir -p build/
	gcc -g -rdynamic -O2 -o build/unique-file-lines unique-file-lines.c
	gcc -g -rdynamic -O2 -o build/sort-lines sort-lines.c
	gcc -g -rdynamic -O2 -o build/line-histogram line-histogram.c
	gcc -g -rdynamic -o build/unique-line-generator unique-line-generator.c





